package com.pspdfkit.internal;

import android.content.Context;
import android.content.res.TypedArray;
import android.graphics.drawable.Drawable;
import androidx.core.content.ContextCompat;
import com.pspdfkit.R;

/* JADX INFO: loaded from: classes3.dex */
public final class cv {
    public final int A;
    public final int B;
    public final int C;
    public final int D;
    public final int E;
    public final int F;
    public final int G;
    public final int H;
    public final int I;
    public final int J;
    public final int K;
    public final int L;
    public final int M;
    public final int N;
    public final int O;
    public final int P;
    public final int Q;
    public final int R;
    public final int a;
    public final int b;
    public final Drawable c;
    public final Drawable d;
    public final Drawable e;
    public final Drawable f;
    public final Drawable g;
    public final Drawable h;
    public final Drawable i;
    public final Drawable j;
    public final Drawable k;
    public final Drawable l;
    public final Drawable m;
    public final Drawable n;
    public final Drawable o;
    public final Drawable p;
    public final Drawable q;
    public final Drawable r;
    public final Drawable s;
    public final Drawable t;
    public final Drawable u;
    public final Drawable v;
    public final Drawable w;
    public final int x;
    public final int y;
    public final int z;

    public cv(Context context) {
        context.getClass();
        TypedArray typedArrayObtainStyledAttributes = context.getTheme().obtainStyledAttributes(null, R.styleable.pspdf__ActionBarIcons, R.attr.pspdf__actionBarIconsStyle, R.style.PSPDFKit_ActionBarIcons);
        typedArrayObtainStyledAttributes.getClass();
        this.a = typedArrayObtainStyledAttributes.getColor(R.styleable.pspdf__ActionBarIcons_pspdf__iconsColor, ContextCompat.getColor(context, R.color.pspdf__onPrimaryLight));
        this.b = typedArrayObtainStyledAttributes.getColor(R.styleable.pspdf__ActionBarIcons_pspdf__iconsColorActivated, ContextCompat.getColor(context, R.color.pspdf__onPrimaryLight));
        int resourceId = typedArrayObtainStyledAttributes.getResourceId(R.styleable.pspdf__ActionBarIcons_pspdf__outlineIcon, R.drawable.pspdf__ic_outline);
        this.x = resourceId;
        int resourceId2 = typedArrayObtainStyledAttributes.getResourceId(R.styleable.pspdf__ActionBarIcons_pspdf__searchIcon, R.drawable.pspdf__ic_search);
        this.y = resourceId2;
        int resourceId3 = typedArrayObtainStyledAttributes.getResourceId(R.styleable.pspdf__ActionBarIcons_pspdf__gridIcon, R.drawable.pspdf__ic_thumbnails);
        this.z = resourceId3;
        int resourceId4 = typedArrayObtainStyledAttributes.getResourceId(R.styleable.pspdf__ActionBarIcons_pspdf__editAnnotationsIcon, R.drawable.pspdf__ic_edit_annotations);
        this.A = resourceId4;
        int resourceId5 = typedArrayObtainStyledAttributes.getResourceId(R.styleable.pspdf__ActionBarIcons_pspdf__aiAssistantIcon, R.drawable.pspdf__ic_ai_assistant);
        this.B = resourceId5;
        int resourceId6 = typedArrayObtainStyledAttributes.getResourceId(R.styleable.pspdf__ActionBarIcons_pspdf__editAnnotationsIconActivated, R.drawable.pspdf__ic_edit_annotations);
        this.C = resourceId6;
        int resourceId7 = typedArrayObtainStyledAttributes.getResourceId(R.styleable.pspdf__ActionBarIcons_pspdf__editContentIcon, R.drawable.pspdf__ic_edit_content);
        this.D = resourceId7;
        int resourceId8 = typedArrayObtainStyledAttributes.getResourceId(R.styleable.pspdf__ActionBarIcons_pspdf__editContentIconActivated, R.drawable.pspdf__ic_edit_content);
        this.E = resourceId8;
        int resourceId9 = typedArrayObtainStyledAttributes.getResourceId(R.styleable.pspdf__ActionBarIcons_pspdf__signatureIcon, R.drawable.pspdf__ic_signature);
        this.F = resourceId9;
        int resourceId10 = typedArrayObtainStyledAttributes.getResourceId(R.styleable.pspdf__ActionBarIcons_pspdf__signatureIconActivated, R.drawable.pspdf__ic_signature);
        this.G = resourceId10;
        int resourceId11 = typedArrayObtainStyledAttributes.getResourceId(R.styleable.pspdf__ActionBarIcons_pspdf__shareIcon, R.drawable.pspdf__ic_share);
        this.H = resourceId11;
        int resourceId12 = typedArrayObtainStyledAttributes.getResourceId(R.styleable.pspdf__ActionBarIcons_pspdf__printIcon, R.drawable.pspdf__ic_print);
        this.I = resourceId12;
        int resourceId13 = typedArrayObtainStyledAttributes.getResourceId(R.styleable.pspdf__ActionBarIcons_pspdf__settingsIcon, R.drawable.pspdf__ic_settings);
        this.J = resourceId13;
        int resourceId14 = typedArrayObtainStyledAttributes.getResourceId(R.styleable.pspdf__ActionBarIcons_pspdf__outlineIconActivated, R.drawable.pspdf__ic_outline);
        this.K = resourceId14;
        int resourceId15 = typedArrayObtainStyledAttributes.getResourceId(R.styleable.pspdf__ActionBarIcons_pspdf__searchIconActivated, R.drawable.pspdf__ic_search);
        this.L = resourceId15;
        int resourceId16 = typedArrayObtainStyledAttributes.getResourceId(R.styleable.pspdf__ActionBarIcons_pspdf__gridIconActivated, R.drawable.pspdf__ic_thumbnails_active);
        this.M = resourceId16;
        int resourceId17 = typedArrayObtainStyledAttributes.getResourceId(R.styleable.pspdf__ActionBarIcons_pspdf__settingsIconActivated, R.drawable.pspdf__ic_settings);
        this.N = resourceId17;
        int resourceId18 = typedArrayObtainStyledAttributes.getResourceId(R.styleable.pspdf__ActionBarIcons_pspdf__readerViewIcon, R.drawable.pspdf__ic_reader_view);
        this.O = resourceId18;
        int resourceId19 = typedArrayObtainStyledAttributes.getResourceId(R.styleable.pspdf__ActionBarIcons_pspdf__readerViewIconActivated, R.drawable.pspdf__ic_reader_view);
        this.P = resourceId19;
        int resourceId20 = typedArrayObtainStyledAttributes.getResourceId(R.styleable.pspdf__ActionBarIcons_pspdf__infoViewIcon, R.drawable.pspdf__ic_info);
        this.Q = resourceId20;
        int resourceId21 = typedArrayObtainStyledAttributes.getResourceId(R.styleable.pspdf__ActionBarIcons_pspdf__infoViewIconActivated, R.drawable.pspdf__ic_info);
        this.R = resourceId21;
        typedArrayObtainStyledAttributes.recycle();
        this.c = a80.b(context, resourceId3);
        this.d = a80.b(context, resourceId16);
        this.e = a80.b(context, resourceId);
        this.f = a80.b(context, resourceId14);
        this.g = a80.b(context, resourceId2);
        this.h = a80.b(context, resourceId15);
        this.i = a80.b(context, resourceId4);
        this.j = a80.b(context, resourceId5);
        this.k = a80.b(context, resourceId6);
        this.l = a80.b(context, resourceId7);
        this.m = a80.b(context, resourceId8);
        this.n = a80.b(context, resourceId9);
        this.o = a80.b(context, resourceId10);
        this.p = a80.b(context, resourceId11);
        this.q = a80.b(context, resourceId12);
        this.r = a80.b(context, resourceId13);
        this.s = a80.b(context, resourceId17);
        this.t = a80.b(context, resourceId20);
        this.u = a80.b(context, resourceId21);
        this.v = a80.b(context, resourceId18);
        this.w = a80.b(context, resourceId19);
    }
}
