package com.microsoft.intune.mam.client;

/* JADX INFO: loaded from: classes3.dex */
public enum MAMSDKCapability {
    STRICT_SAVE_UPN,
    STRICT_UNREGISTER_ACCOUNT_WITHIN_ACQUIRE_TOKEN,
    SINGLE_IDENTITY_ENROLLMENT_STATUS_CACHE_DEPRECATIONS,
    NEW_IDENTITY_API,
    USER_LOCAL_SETTINGS_V1,
    APP_PROMPT_USER_CONSENT_LOG_UPLOAD
}
