package com.microsoft.identity.common.nativeauth.internal.util;

import com.microsoft.identity.common.java.nativeauth.commands.parameters.BaseSignInTokenCommandParameters;
import com.microsoft.identity.common.java.nativeauth.commands.parameters.JITContinueCommandParameters;
import com.microsoft.identity.common.java.nativeauth.commands.parameters.JITIntrospectCommandParameters;
import com.microsoft.identity.common.java.nativeauth.commands.parameters.MFASubmitChallengeCommandParameters;
import com.microsoft.identity.common.java.nativeauth.commands.parameters.SignInStartCommandParameters;
import com.microsoft.identity.common.java.nativeauth.commands.parameters.SignInSubmitCodeCommandParameters;
import com.microsoft.identity.common.java.nativeauth.commands.parameters.SignInSubmitPasswordCommandParameters;
import com.microsoft.identity.common.java.nativeauth.commands.parameters.SignInWithContinuationTokenCommandParameters;
import com.microsoft.identity.common.java.request.SdkType;
import java.util.List;

/* JADX INFO: loaded from: classes14.dex */
public class CommandUtil {
    /* JADX WARN: Multi-variable type inference failed */
    public static SignInStartCommandParameters createSignInStartCommandParametersWithScopes(SignInStartCommandParameters signInStartCommandParameters, List<String> list) {
        return ((SignInStartCommandParameters.SignInStartCommandParametersBuilder) ((SignInStartCommandParameters.SignInStartCommandParametersBuilder) signInStartCommandParameters.toBuilder().scopes(list)).correlationId(signInStartCommandParameters.getCorrelationId())).build();
    }

    /* JADX WARN: Multi-variable type inference failed */
    public static SignInWithContinuationTokenCommandParameters createSignInWithContinuationTokenCommandParametersWithScopes(SignInWithContinuationTokenCommandParameters signInWithContinuationTokenCommandParameters, List<String> list) {
        return ((SignInWithContinuationTokenCommandParameters.SignInWithContinuationTokenCommandParametersBuilder) ((SignInWithContinuationTokenCommandParameters.SignInWithContinuationTokenCommandParametersBuilder) signInWithContinuationTokenCommandParameters.toBuilder().scopes(list)).correlationId(signInWithContinuationTokenCommandParameters.getCorrelationId())).build();
    }

    /* JADX WARN: Multi-variable type inference failed */
    public static SignInSubmitCodeCommandParameters createSignInSubmitCodeCommandParametersWithScopes(SignInSubmitCodeCommandParameters signInSubmitCodeCommandParameters, List<String> list) {
        return ((SignInSubmitCodeCommandParameters.SignInSubmitCodeCommandParametersBuilder) ((SignInSubmitCodeCommandParameters.SignInSubmitCodeCommandParametersBuilder) signInSubmitCodeCommandParameters.toBuilder().scopes(list)).correlationId(signInSubmitCodeCommandParameters.getCorrelationId())).isMFAGrantType(signInSubmitCodeCommandParameters.getIsMFAGrantType()).build();
    }

    /* JADX WARN: Multi-variable type inference failed */
    public static SignInSubmitPasswordCommandParameters createSignInSubmitPasswordCommandParametersWithScopes(SignInSubmitPasswordCommandParameters signInSubmitPasswordCommandParameters, String str, List<String> list) {
        return ((SignInSubmitPasswordCommandParameters.SignInSubmitPasswordCommandParametersBuilder) ((SignInSubmitPasswordCommandParameters.SignInSubmitPasswordCommandParametersBuilder) signInSubmitPasswordCommandParameters.toBuilder().scopes(list)).correlationId(str)).build();
    }

    /* JADX WARN: Multi-variable type inference failed */
    public static SignInSubmitPasswordCommandParameters createSignInSubmitPasswordCommandParameters(SignInStartCommandParameters signInStartCommandParameters, String str, String str2) {
        return ((SignInSubmitPasswordCommandParameters.SignInSubmitPasswordCommandParametersBuilder) ((SignInSubmitPasswordCommandParameters.SignInSubmitPasswordCommandParametersBuilder) ((SignInSubmitPasswordCommandParameters.SignInSubmitPasswordCommandParametersBuilder) ((SignInSubmitPasswordCommandParameters.SignInSubmitPasswordCommandParametersBuilder) ((SignInSubmitPasswordCommandParameters.SignInSubmitPasswordCommandParametersBuilder) ((SignInSubmitPasswordCommandParameters.SignInSubmitPasswordCommandParametersBuilder) ((SignInSubmitPasswordCommandParameters.SignInSubmitPasswordCommandParametersBuilder) ((SignInSubmitPasswordCommandParameters.SignInSubmitPasswordCommandParametersBuilder) ((SignInSubmitPasswordCommandParameters.SignInSubmitPasswordCommandParametersBuilder) ((SignInSubmitPasswordCommandParameters.SignInSubmitPasswordCommandParametersBuilder) ((SignInSubmitPasswordCommandParameters.SignInSubmitPasswordCommandParametersBuilder) ((SignInSubmitPasswordCommandParameters.SignInSubmitPasswordCommandParametersBuilder) ((SignInSubmitPasswordCommandParameters.SignInSubmitPasswordCommandParametersBuilder) ((SignInSubmitPasswordCommandParameters.SignInSubmitPasswordCommandParametersBuilder) ((SignInSubmitPasswordCommandParameters.SignInSubmitPasswordCommandParametersBuilder) ((SignInSubmitPasswordCommandParameters.SignInSubmitPasswordCommandParametersBuilder) SignInSubmitPasswordCommandParameters.builder().platformComponents(signInStartCommandParameters.getPlatformComponents())).applicationName(signInStartCommandParameters.getApplicationName())).applicationVersion(signInStartCommandParameters.getApplicationVersion())).clientId(signInStartCommandParameters.getClientId())).isSharedDevice(signInStartCommandParameters.isSharedDevice())).redirectUri(signInStartCommandParameters.getRedirectUri())).oAuth2TokenCache(signInStartCommandParameters.getOAuth2TokenCache())).requiredBrokerProtocolVersion(signInStartCommandParameters.getRequiredBrokerProtocolVersion())).sdkType(SdkType.MSAL)).sdkVersion(signInStartCommandParameters.getSdkVersion())).powerOptCheckEnabled(signInStartCommandParameters.isPowerOptCheckEnabled())).authority(signInStartCommandParameters.getAuthority())).continuationToken(str2).password(signInStartCommandParameters.getPassword()).scopes(signInStartCommandParameters.getScopes())).correlationId(str)).claimsRequestJson(signInStartCommandParameters.getClaimsRequestJson())).challengeType(signInStartCommandParameters.getChallengeType())).build();
    }

    /* JADX WARN: Multi-variable type inference failed */
    public static SignInWithContinuationTokenCommandParameters createSignInWithContinuationTokenCommandParameters(BaseSignInTokenCommandParameters baseSignInTokenCommandParameters, String str, String str2) {
        return ((SignInWithContinuationTokenCommandParameters.SignInWithContinuationTokenCommandParametersBuilder) ((SignInWithContinuationTokenCommandParameters.SignInWithContinuationTokenCommandParametersBuilder) ((SignInWithContinuationTokenCommandParameters.SignInWithContinuationTokenCommandParametersBuilder) ((SignInWithContinuationTokenCommandParameters.SignInWithContinuationTokenCommandParametersBuilder) ((SignInWithContinuationTokenCommandParameters.SignInWithContinuationTokenCommandParametersBuilder) ((SignInWithContinuationTokenCommandParameters.SignInWithContinuationTokenCommandParametersBuilder) ((SignInWithContinuationTokenCommandParameters.SignInWithContinuationTokenCommandParametersBuilder) ((SignInWithContinuationTokenCommandParameters.SignInWithContinuationTokenCommandParametersBuilder) ((SignInWithContinuationTokenCommandParameters.SignInWithContinuationTokenCommandParametersBuilder) ((SignInWithContinuationTokenCommandParameters.SignInWithContinuationTokenCommandParametersBuilder) ((SignInWithContinuationTokenCommandParameters.SignInWithContinuationTokenCommandParametersBuilder) ((SignInWithContinuationTokenCommandParameters.SignInWithContinuationTokenCommandParametersBuilder) ((SignInWithContinuationTokenCommandParameters.SignInWithContinuationTokenCommandParametersBuilder) ((SignInWithContinuationTokenCommandParameters.SignInWithContinuationTokenCommandParametersBuilder) ((SignInWithContinuationTokenCommandParameters.SignInWithContinuationTokenCommandParametersBuilder) SignInWithContinuationTokenCommandParameters.builder().authenticationScheme(baseSignInTokenCommandParameters.getAuthenticationScheme())).platformComponents(baseSignInTokenCommandParameters.getPlatformComponents())).applicationName(baseSignInTokenCommandParameters.getApplicationName())).applicationVersion(baseSignInTokenCommandParameters.getApplicationVersion())).clientId(baseSignInTokenCommandParameters.getClientId())).isSharedDevice(baseSignInTokenCommandParameters.isSharedDevice())).redirectUri(baseSignInTokenCommandParameters.getRedirectUri())).oAuth2TokenCache(baseSignInTokenCommandParameters.getOAuth2TokenCache())).requiredBrokerProtocolVersion(baseSignInTokenCommandParameters.getRequiredBrokerProtocolVersion())).sdkType(SdkType.MSAL)).sdkVersion(baseSignInTokenCommandParameters.getSdkVersion())).powerOptCheckEnabled(baseSignInTokenCommandParameters.isPowerOptCheckEnabled())).authority(baseSignInTokenCommandParameters.getAuthority())).continuationToken(str2).correlationId(str)).challengeType(baseSignInTokenCommandParameters.getChallengeType())).build();
    }

    /* JADX WARN: Multi-variable type inference failed */
    public static JITIntrospectCommandParameters createJITIntrospectCommandParameters(BaseSignInTokenCommandParameters baseSignInTokenCommandParameters, String str, String str2) {
        return ((JITIntrospectCommandParameters.JITIntrospectCommandParametersBuilder) ((JITIntrospectCommandParameters.JITIntrospectCommandParametersBuilder) ((JITIntrospectCommandParameters.JITIntrospectCommandParametersBuilder) ((JITIntrospectCommandParameters.JITIntrospectCommandParametersBuilder) ((JITIntrospectCommandParameters.JITIntrospectCommandParametersBuilder) ((JITIntrospectCommandParameters.JITIntrospectCommandParametersBuilder) ((JITIntrospectCommandParameters.JITIntrospectCommandParametersBuilder) ((JITIntrospectCommandParameters.JITIntrospectCommandParametersBuilder) ((JITIntrospectCommandParameters.JITIntrospectCommandParametersBuilder) ((JITIntrospectCommandParameters.JITIntrospectCommandParametersBuilder) ((JITIntrospectCommandParameters.JITIntrospectCommandParametersBuilder) ((JITIntrospectCommandParameters.JITIntrospectCommandParametersBuilder) ((JITIntrospectCommandParameters.JITIntrospectCommandParametersBuilder) ((JITIntrospectCommandParameters.JITIntrospectCommandParametersBuilder) JITIntrospectCommandParameters.builder().platformComponents(baseSignInTokenCommandParameters.getPlatformComponents())).applicationName(baseSignInTokenCommandParameters.getApplicationName())).applicationVersion(baseSignInTokenCommandParameters.getApplicationVersion())).clientId(baseSignInTokenCommandParameters.getClientId())).isSharedDevice(baseSignInTokenCommandParameters.isSharedDevice())).redirectUri(baseSignInTokenCommandParameters.getRedirectUri())).oAuth2TokenCache(baseSignInTokenCommandParameters.getOAuth2TokenCache())).requiredBrokerProtocolVersion(baseSignInTokenCommandParameters.getRequiredBrokerProtocolVersion())).sdkType(SdkType.MSAL)).sdkVersion(baseSignInTokenCommandParameters.getSdkVersion())).powerOptCheckEnabled(baseSignInTokenCommandParameters.isPowerOptCheckEnabled())).authority(baseSignInTokenCommandParameters.getAuthority())).continuationToken(str2).correlationId(str)).challengeType(baseSignInTokenCommandParameters.getChallengeType())).build();
    }

    /* JADX WARN: Multi-variable type inference failed */
    public static JITContinueCommandParameters createJITContinueCommandParameters(BaseSignInTokenCommandParameters baseSignInTokenCommandParameters, String str, String str2, String str3) {
        return ((JITContinueCommandParameters.JITContinueCommandParametersBuilder) ((JITContinueCommandParameters.JITContinueCommandParametersBuilder) ((JITContinueCommandParameters.JITContinueCommandParametersBuilder) ((JITContinueCommandParameters.JITContinueCommandParametersBuilder) ((JITContinueCommandParameters.JITContinueCommandParametersBuilder) ((JITContinueCommandParameters.JITContinueCommandParametersBuilder) ((JITContinueCommandParameters.JITContinueCommandParametersBuilder) ((JITContinueCommandParameters.JITContinueCommandParametersBuilder) ((JITContinueCommandParameters.JITContinueCommandParametersBuilder) ((JITContinueCommandParameters.JITContinueCommandParametersBuilder) ((JITContinueCommandParameters.JITContinueCommandParametersBuilder) ((JITContinueCommandParameters.JITContinueCommandParametersBuilder) ((JITContinueCommandParameters.JITContinueCommandParametersBuilder) ((JITContinueCommandParameters.JITContinueCommandParametersBuilder) ((JITContinueCommandParameters.JITContinueCommandParametersBuilder) JITContinueCommandParameters.builder().authenticationScheme(baseSignInTokenCommandParameters.getAuthenticationScheme())).platformComponents(baseSignInTokenCommandParameters.getPlatformComponents())).applicationName(baseSignInTokenCommandParameters.getApplicationName())).applicationVersion(baseSignInTokenCommandParameters.getApplicationVersion())).clientId(baseSignInTokenCommandParameters.getClientId())).isSharedDevice(baseSignInTokenCommandParameters.isSharedDevice())).redirectUri(baseSignInTokenCommandParameters.getRedirectUri())).oAuth2TokenCache(baseSignInTokenCommandParameters.getOAuth2TokenCache())).requiredBrokerProtocolVersion(baseSignInTokenCommandParameters.getRequiredBrokerProtocolVersion())).sdkType(SdkType.MSAL)).sdkVersion(baseSignInTokenCommandParameters.getSdkVersion())).powerOptCheckEnabled(baseSignInTokenCommandParameters.isPowerOptCheckEnabled())).authority(baseSignInTokenCommandParameters.getAuthority())).continuationToken(str3).correlationId(str)).challengeType(baseSignInTokenCommandParameters.getChallengeType())).grantType(str2).build();
    }

    /* JADX WARN: Multi-variable type inference failed */
    public static MFASubmitChallengeCommandParameters createMFASubmitChallengeCommandParametersWithScopes(MFASubmitChallengeCommandParameters mFASubmitChallengeCommandParameters, List<String> list) {
        return ((MFASubmitChallengeCommandParameters.MFASubmitChallengeCommandParametersBuilder) ((MFASubmitChallengeCommandParameters.MFASubmitChallengeCommandParametersBuilder) mFASubmitChallengeCommandParameters.toBuilder().scopes(list)).correlationId(mFASubmitChallengeCommandParameters.getCorrelationId())).build();
    }

    /* JADX WARN: Multi-variable type inference failed */
    public static SignInSubmitCodeCommandParameters createSignInSubmitCodeCommandParameters(MFASubmitChallengeCommandParameters mFASubmitChallengeCommandParameters) {
        return ((SignInSubmitCodeCommandParameters.SignInSubmitCodeCommandParametersBuilder) ((SignInSubmitCodeCommandParameters.SignInSubmitCodeCommandParametersBuilder) ((SignInSubmitCodeCommandParameters.SignInSubmitCodeCommandParametersBuilder) ((SignInSubmitCodeCommandParameters.SignInSubmitCodeCommandParametersBuilder) ((SignInSubmitCodeCommandParameters.SignInSubmitCodeCommandParametersBuilder) ((SignInSubmitCodeCommandParameters.SignInSubmitCodeCommandParametersBuilder) ((SignInSubmitCodeCommandParameters.SignInSubmitCodeCommandParametersBuilder) ((SignInSubmitCodeCommandParameters.SignInSubmitCodeCommandParametersBuilder) ((SignInSubmitCodeCommandParameters.SignInSubmitCodeCommandParametersBuilder) ((SignInSubmitCodeCommandParameters.SignInSubmitCodeCommandParametersBuilder) ((SignInSubmitCodeCommandParameters.SignInSubmitCodeCommandParametersBuilder) ((SignInSubmitCodeCommandParameters.SignInSubmitCodeCommandParametersBuilder) ((SignInSubmitCodeCommandParameters.SignInSubmitCodeCommandParametersBuilder) ((SignInSubmitCodeCommandParameters.SignInSubmitCodeCommandParametersBuilder) ((SignInSubmitCodeCommandParameters.SignInSubmitCodeCommandParametersBuilder) ((SignInSubmitCodeCommandParameters.SignInSubmitCodeCommandParametersBuilder) SignInSubmitCodeCommandParameters.builder().platformComponents(mFASubmitChallengeCommandParameters.getPlatformComponents())).applicationName(mFASubmitChallengeCommandParameters.getApplicationName())).applicationVersion(mFASubmitChallengeCommandParameters.getApplicationVersion())).clientId(mFASubmitChallengeCommandParameters.getClientId())).isSharedDevice(mFASubmitChallengeCommandParameters.isSharedDevice())).redirectUri(mFASubmitChallengeCommandParameters.getRedirectUri())).oAuth2TokenCache(mFASubmitChallengeCommandParameters.getOAuth2TokenCache())).requiredBrokerProtocolVersion(mFASubmitChallengeCommandParameters.getRequiredBrokerProtocolVersion())).sdkType(SdkType.MSAL)).sdkVersion(mFASubmitChallengeCommandParameters.getSdkVersion())).powerOptCheckEnabled(mFASubmitChallengeCommandParameters.isPowerOptCheckEnabled())).authority(mFASubmitChallengeCommandParameters.getAuthority())).continuationToken(mFASubmitChallengeCommandParameters.continuationToken).code(mFASubmitChallengeCommandParameters.challenge).scopes(mFASubmitChallengeCommandParameters.getScopes())).correlationId(mFASubmitChallengeCommandParameters.getCorrelationId())).challengeType(mFASubmitChallengeCommandParameters.getChallengeType())).claimsRequestJson(mFASubmitChallengeCommandParameters.claimsRequestJson)).isMFAGrantType(true).build();
    }
}
