package com.pspdfkit.internal.jni;

/* JADX INFO: loaded from: classes3.dex */
public enum NativeDocumentIntegrityStatus {
    OK,
    TAMPERED_DOCUMENT,
    FAILED_RETRIEVE_SIGNATURE_CONTENTS,
    FAILED_RETRIEVE_BYTE_RANGE,
    FAILED_COMPUTE_DIGEST,
    FAILED_RETRIEVE_SIGNING_CERTIFICATE,
    FAILED_RETRIEVE_PUBLIC_KEY,
    FAILED_ENCRYPTION_PADDING,
    FAILED_UNSUPPORTED_SIGNATURE_TYPE,
    TAMPERED_OR_INVALID_TIMESTAMP,
    GENERAL_FAILURE
}
