package com.microsoft.intune.mam.client.telemetry.events;

import java.util.concurrent.TimeUnit;

/* JADX INFO: loaded from: classes3.dex */
public enum TrackedOccurrence implements TrackedOccurrenceType {
    INVALID,
    IPC_RETRY_WORKED,
    CHROME_PACKAGE_SERVICE_BLOCKED,
    MAM_JOB_CONFLICTED_WITH_APPS,
    ACTIVITY_STARTED_FROM_UNMANAGED(TimeUnit.DAYS.toMillis(7)),
    ENCRYPTION_REQUIREMENT_RESOLVED,
    DEFAULT_ENROLL_INTERACTIVE_AUTH,
    DEFAULT_ENROLL_FAILED,
    ENROLL_FAILED_WITH_WRONG_USER,
    ACCESS_BLOCKED_COMPANY_PORTAL_OUTDATED,
    ACCESS_BLOCKED_MIN_OS_VERSION,
    ACCESS_BLOCKED_MAX_OS_VERSION,
    ACCESS_BLOCKED_MIN_OS_PATCH_VERSION,
    ACCESS_BLOCKED_MIN_APP_VERSION,
    ACCESS_BLOCKED_MIN_CP_VERSION,
    ACCESS_BLOCKED_MIN_CP_FRESHNESS,
    PLAY_SERVICE_UNAVAILABLE,
    ACCESS_BLOCKED_NON_COMPLIANT_DEVICE,
    ACCESS_BLOCKED_POLICY_REQUIRED,
    ACCESS_BLOCKED_POLICY_VERSION,
    ACCESS_BLOCKED_PIN_ATTEMPT_LIMIT_REACHED,
    ACCESS_BLOCKED_PERMISSIONS_DENIED,
    ACCESS_BLOCKED_DEVICE,
    ACCESS_BLOCKED_DEVICE_MANUFACTURER,
    ACCESS_BLOCKED_DEVICE_MODEL,
    ACCESS_BLOCKED_DEVICE_WITHOUT_LOCK,
    WIPED_DEVICE_WITHOUT_LOCK,
    ACCESS_BLOCKED_DEVICE_LOCK_COMPLEXITY,
    WIPED_DEVICE_LOCK_COMPLEXITY,
    PIN_EXPIRY_TIMEOUT_EXCEEDED,
    CHECKIN_OFFLINE_TIMEOUT_EXCEEDED,
    POLICY_UNTARGETED,
    AUTHENTICATION_CANCELED,
    AUTHENTICATION_FAILED,
    SSL_CERT_VALIDATION_FAILED_WRONG_PUBLIC_KEY,
    SSL_CERT_VALIDATION_FAILED_NOT_SIGNED_BY_ROOT,
    SSL_CERT_VALIDATION_FAILED_MSIT_CERT_NOT_FOUND,
    APP_CONFIG_CONFLICT_DETECTED(TimeUnit.DAYS.toMillis(7)),
    MAM_KEY_PROTECTOR_ENCRYPTION_FAILED_RSA,
    MAM_KEY_PROTECTOR_ENCRYPTION_FAILED_AES,
    VERIFY_APPS_TIMED_OUT,
    DEVICE_ATTESTATION_PROCESSING_RECHECK_PROMPT,
    DEVICE_ATTESTATION_MAM_SERVICE_NOT_PARSABLE,
    DEVICE_ATTESTATION_MAM_SERVICE_NONCE_MISMATCH,
    DEVICE_ATTESTATION_RESULTS_UNTRUSTED,
    DEVICE_ATTESTATION_NEEDS_AUTH,
    DB_HARDENING_POLICY_UPDATE_BLOCKED,
    DB_HARDENING_FORCED_CHECKIN,
    LOADER_LIBRARY_PATH_MODIFIED_ARM64_LOLLIPOP,
    TEXTCLASSIFIER_BLOCKED_CONVERSATION_ACTION,
    REWRITE_ACTIVITY_INTENT_USING_CONTENT_URI_IDENTITY,
    PROXY_DOESNT_OVERRIDE_PUBLIC_METHOD,
    DB_ROW_LONG_PATH,
    KEPT_ROW_IN_PENDING_OPS_TABLE_RESULT_PENDING,
    ALLOWED_ACCOUNTS_CONFIGURATION_CONFLICT(TimeUnit.DAYS.toMillis(7)),
    TOO_MANY_ROWS_IN_PENDING_FILE_ENCRYPTION_OPS_TABLE,
    FILE_DECRYPT_FAILED_ERR_ENCRYPTION_CHANGE_UNSAFE,
    INTERCEPTED_SUPPORT_VIEW_FROM_INTERNAL_CLASSLOADER,
    ALARM_MANAGER_CANCEL_SECURITY_EXCEPTION,
    SERVICE_ON_BIND_BLOCKED,
    ONNEWINTENT_IDENTITY_SWITCH_FAILURE_IGNORED,
    DEFAULT_REDIRECT_URI_IN_USE(TimeUnit.DAYS.toMillis(28)),
    LEGACY_PRINTING(TimeUnit.DAYS.toMillis(14)),
    IDENTITY_SERVICE_CONNECTION_CLASS_CAST_EXCEPTION,
    ACTIVITY_RECREATED_FOR_TAMPERING,
    AUDIT_INSTRUMENTATION_CHECK,
    IPC_FAILURE_OFFLINE,
    CLOCK_STATUS_NETWORK_TIMEOUT,
    CLOCK_STATUS_TIMEOUT_UI,
    CLOCK_STATUS_INCOMPLETE_NOTIFICATION_DECISION,
    APPSEARCHMANAGER_USAGE(TimeUnit.DAYS.toMillis(14)),
    CLIPBOARD_LISTENER_FIXUP,
    MAMSERVICE_TOKEN_WRONG_RESOURCE(TimeUnit.DAYS.toMillis(1)),
    MAMSERVICE_TOKEN_WRONG_USER_ID(TimeUnit.DAYS.toMillis(1)),
    MAMSERVICE_TOKEN_WRONG_TENANT_ID(TimeUnit.DAYS.toMillis(1)),
    RASP_ROOT_DETECTED,
    RASP_FILE_TAMPER_DETECTED,
    RASP_CERTIFICATE_TAMPER_DETECTED,
    RASP_HOOK_DETECTED,
    OGP_EXPIRED,
    FAILED_TO_GET_AGENT_OUT_OF_RESTRICTED_BUCKET,
    SUCCESSFULLY_GOT_AGENT_OUT_OF_RESTRICTED_BUCKET,
    POST_INIT_PROTECTED_SUCCESSFUL_DOWNLOAD,
    PHOTO_PICKER_DETECTED,
    CLOUD_MEDIA_PROVIDER_DETECTED(TimeUnit.DAYS.toMillis(1)),
    SDM_BRIDGE_ALLOWED_ACCOUNTS,
    STOP_THREADS_RETRY_WORKED,
    RECEIVED_TRUSTED_ROOTS_CERTIFICATES,
    KNOX_ATTESTATION_FAILED_TO_VALIDATE,
    ORIGIN_CHECK_BLOCKING_SPINNER_THROWS_EXCEPTION,
    ORIGIN_CHECK_BLOCKING_SPINNER_RETRY_SUCCEEDED,
    THREAD_UNSAFE_AFTER_CHANGE_PC_PTRACELESS,
    INTENT_IDENTITY_TAG_NO_AAD_ID(TimeUnit.DAYS.toMillis(1)),
    KNOX_ATTESTATION_REQUIRED,
    KNOX_LICENSE_ACTIVATION_REQUIRED,
    FIND_CLASS_IN_CLASSLOADER,
    NESTED_POLICY_WINDOW_MANAGER_DETECTED_AND_UNWRAPPED(TimeUnit.DAYS.toMillis(1)),
    MAX_APP_SHORTCUTS_USED,
    APP_PIN_RESET_REQUESTED,
    USER_PROMPTED_FOR_PERMISSION_TO_UPLOAD_LOG_IN_BACKGROUND,
    USER_GRANTED_LOG_UPLOAD_PERMISSION,
    USER_DENIED_LOG_UPLOAD_PERMISSION,
    PROTECT_CALLED_ON_MANAGED_FILE_TO_UNMANAGED,
    PROTECT_CALLED_ON_UNMANAGED_FILE_TO_MANAGED,
    CL_TIMERS_NULL_IDENTITY,
    MMA_FROM_SINGLE_IDENTITY;

    private final long mThrottleMs;

    TrackedOccurrence() {
        this(DEFAULT_THROTTLE_MS);
    }

    TrackedOccurrence(long j) {
        this.mThrottleMs = j;
    }

    @Override // com.microsoft.intune.mam.client.telemetry.events.TrackedOccurrenceType
    public String getName() {
        return name();
    }

    @Override // com.microsoft.intune.mam.client.telemetry.events.TrackedOccurrenceType
    public long getThrottleMs() {
        return this.mThrottleMs;
    }
}
