package com.google.android.gms.measurement.internal;

import android.content.Context;
import com.amplitude.api.Constants;
import com.microsoft.intune.mam.policy.MAMWERetryScheduler;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/* JADX INFO: compiled from: com.google.android.gms:play-services-measurement-impl@@17.2.3 */
/* JADX INFO: loaded from: classes11.dex */
public final class zzap {
    public static zzez<Long> zzaa;
    public static zzez<Integer> zzab;
    public static zzez<Long> zzac;
    public static zzez<Integer> zzad;
    public static zzez<Integer> zzae;
    public static zzez<Integer> zzaf;
    public static zzez<Integer> zzag;
    public static zzez<Long> zzah;
    public static zzez<Boolean> zzai;
    public static zzez<String> zzaj;
    public static zzez<Long> zzak;
    public static zzez<Integer> zzal;
    public static zzez<Double> zzam;
    public static zzez<Integer> zzan;
    public static zzez<Integer> zzao;
    public static zzez<Boolean> zzap;
    public static zzez<Boolean> zzaq;
    public static zzez<Boolean> zzar;
    public static zzez<Boolean> zzas;
    public static zzez<Boolean> zzat;
    public static zzez<Boolean> zzau;
    public static zzez<Boolean> zzav;
    public static zzez<Boolean> zzaw;
    public static zzez<Boolean> zzax;
    public static zzez<Boolean> zzay;
    public static zzez<Boolean> zzaz;
    public static zzez<Boolean> zzba;
    public static zzez<Boolean> zzbb;
    public static zzez<Boolean> zzbc;
    public static zzez<Boolean> zzbd;
    public static zzez<Boolean> zzbe;
    public static zzez<Boolean> zzbf;
    public static zzez<Boolean> zzbg;
    public static zzez<Boolean> zzbh;
    public static zzez<Boolean> zzbi;
    public static zzez<Boolean> zzbj;
    public static zzez<Boolean> zzbk;
    public static zzez<Boolean> zzbl;
    public static zzez<Boolean> zzbm;
    public static zzez<Boolean> zzbn;
    public static zzez<Boolean> zzbo;
    public static zzez<Boolean> zzbp;
    public static zzez<Boolean> zzbq;
    public static zzez<Boolean> zzbr;
    public static zzez<Boolean> zzbs;
    public static zzez<Boolean> zzbt;
    public static zzez<Boolean> zzbu;
    public static zzez<Boolean> zzbv;
    public static zzez<Boolean> zzbw;
    public static zzez<Boolean> zzbx;
    public static zzez<Boolean> zzby;
    public static zzez<Boolean> zzbz;
    public static zzez<Boolean> zzca;
    public static zzez<Boolean> zzcb;
    public static zzez<Boolean> zzcc;
    public static zzez<Boolean> zzcd;
    public static zzez<Boolean> zzce;
    public static zzez<Boolean> zzcf;
    public static zzez<Boolean> zzcg;
    public static zzez<Boolean> zzch;
    public static zzez<Boolean> zzci;
    public static zzez<Boolean> zzcj;
    public static zzez<Boolean> zzck;
    public static zzez<Boolean> zzcl;
    public static zzez<Boolean> zzcm;
    public static zzez<Boolean> zzcn;
    public static zzez<Boolean> zzco;
    public static zzez<Boolean> zzcp;
    public static zzez<Boolean> zzcq;
    public static zzez<Boolean> zzcr;
    public static zzez<Boolean> zzcs;
    public static zzez<Boolean> zzct;
    public static zzez<Boolean> zzcu;
    public static zzez<Boolean> zzcv;
    public static zzez<Boolean> zzcw;
    public static zzez<Boolean> zzcx;
    public static zzez<Boolean> zzcy;
    public static zzez<Boolean> zzcz;
    public static zzez<Boolean> zzda;
    public static zzez<Boolean> zzdb;
    public static zzez<Boolean> zzdc;
    public static zzez<Boolean> zzdd;
    public static zzez<Boolean> zzde;
    public static zzez<Boolean> zzdf;
    public static zzez<Boolean> zzdg;
    private static zzez<Boolean> zzdj;
    private static zzez<Boolean> zzdk;
    public static zzez<Long> zzq;
    public static zzez<Long> zzr;
    public static zzez<Long> zzs;
    public static zzez<Long> zzt;
    public static zzez<Long> zzu;
    public static zzez<Long> zzv;
    public static zzez<Long> zzw;
    public static zzez<Long> zzx;
    public static zzez<Long> zzy;
    public static zzez<Long> zzz;
    private static List<zzez<?>> zzdh = Collections.synchronizedList(new ArrayList());
    private static Set<zzez<?>> zzdi = Collections.synchronizedSet(new HashSet());
    public static zzez<Long> zza = zza("measurement.ad_id_cache_time", 10000L, 10000L, zzas.zza);
    public static zzez<Long> zzb = zza("measurement.monitoring.sample_period_millis", 86400000L, 86400000L, zzar.zza);
    public static zzez<Long> zzc = zza("measurement.config.cache_time", 86400000L, 3600000L, zzbo.zza);
    public static zzez<String> zzd = zza("measurement.config.url_scheme", "https", "https", zzbx.zza);
    public static zzez<String> zze = zza("measurement.config.url_authority", "app-measurement.com", "app-measurement.com", zzck.zza);
    public static zzez<Integer> zzf = zza("measurement.upload.max_bundles", 100, 100, zzct.zza);
    public static zzez<Integer> zzg = zza("measurement.upload.max_batch_size", 65536, 65536, zzdg.zza);
    public static zzez<Integer> zzh = zza("measurement.upload.max_bundle_size", 65536, 65536, zzdp.zza);
    public static zzez<Integer> zzi = zza("measurement.upload.max_events_per_bundle", 1000, 1000, zzec.zza);
    public static zzez<Integer> zzj = zza("measurement.upload.max_events_per_day", 100000, 100000, zzel.zza);
    public static zzez<Integer> zzk = zza("measurement.upload.max_error_events_per_day", 1000, 1000, zzau.zza);
    public static zzez<Integer> zzl = zza("measurement.upload.max_public_events_per_day", 50000, 50000, zzbd.zza);
    public static zzez<Integer> zzm = zza("measurement.upload.max_conversions_per_day", 10000, 10000, zzbg.zza);
    public static zzez<Integer> zzn = zza("measurement.upload.max_realtime_events_per_day", 10, 10, zzbf.zza);
    public static zzez<Integer> zzo = zza("measurement.store.max_stored_events_per_app", 100000, 100000, zzbi.zza);
    public static zzez<String> zzp = zza("measurement.upload.url", "https://app-measurement.com/a", "https://app-measurement.com/a", zzbh.zza);

    public static Map<String, String> zza(Context context) {
        com.google.android.gms.internal.measurement.zzbx zzbxVarZza = com.google.android.gms.internal.measurement.zzbx.zza(context.getContentResolver(), com.google.android.gms.internal.measurement.zzcm.zza("com.google.android.gms.measurement"));
        return zzbxVarZza == null ? Collections.emptyMap() : zzbxVarZza.zza();
    }

    private static <V> zzez<V> zza(String str, V v, V v2, zzex<V> zzexVar) {
        zzez<V> zzezVar = new zzez<>(str, v, v2, zzexVar);
        zzdh.add(zzezVar);
        return zzezVar;
    }

    static final /* synthetic */ Long zzdd() {
        if (zzfa.zza != null) {
            zzw zzwVar = zzfa.zza;
        }
        return Long.valueOf(com.google.android.gms.internal.measurement.zzjd.zzc());
    }

    static {
        Long lValueOf = Long.valueOf(MAMWERetryScheduler.DEFAULT_UNLICENSED_RETRY_INTERVAL_MS);
        zzq = zza("measurement.upload.backoff_period", lValueOf, lValueOf, zzbk.zza);
        zzr = zza("measurement.upload.window_interval", 3600000L, 3600000L, zzbj.zza);
        zzs = zza("measurement.upload.interval", 3600000L, 3600000L, zzbm.zza);
        zzt = zza("measurement.upload.realtime_upload_interval", 10000L, 10000L, zzbl.zza);
        zzu = zza("measurement.upload.debug_upload_interval", 1000L, 1000L, zzbn.zza);
        zzv = zza("measurement.upload.minimum_delay", 500L, 500L, zzbq.zza);
        zzw = zza("measurement.alarm_manager.minimum_interval", 60000L, 60000L, zzbp.zza);
        zzx = zza("measurement.upload.stale_data_deletion_interval", 86400000L, 86400000L, zzbs.zza);
        zzy = zza("measurement.upload.refresh_blacklisted_config_interval", 604800000L, 604800000L, zzbr.zza);
        zzz = zza("measurement.upload.initial_upload_delay_time", 15000L, 15000L, zzbu.zza);
        Long lValueOf2 = Long.valueOf(Constants.SESSION_TIMEOUT_MILLIS);
        zzaa = zza("measurement.upload.retry_time", lValueOf2, lValueOf2, zzbt.zza);
        zzab = zza("measurement.upload.retry_count", 6, 6, zzbw.zza);
        zzac = zza("measurement.upload.max_queue_time", 2419200000L, 2419200000L, zzbv.zza);
        zzad = zza("measurement.lifetimevalue.max_currency_tracked", 4, 4, zzby.zza);
        zzae = zza("measurement.audience.filter_result_max_count", 200, 200, zzca.zza);
        zzaf = zza("measurement.upload.max_public_user_properties", 25, 25, null);
        zzag = zza("measurement.upload.max_event_name_cardinality", 500, 500, null);
        zzah = zza("measurement.service_client.idle_disconnect_millis", 5000L, 5000L, zzbz.zza);
        zzai = zza("measurement.test.boolean_flag", false, false, zzcc.zza);
        zzaj = zza("measurement.test.string_flag", "---", "---", zzcb.zza);
        zzak = zza("measurement.test.long_flag", -1L, -1L, zzce.zza);
        zzal = zza("measurement.test.int_flag", -2, -2, zzcd.zza);
        Double dValueOf = Double.valueOf(-3.0d);
        zzam = zza("measurement.test.double_flag", dValueOf, dValueOf, zzcg.zza);
        zzan = zza("measurement.experiment.max_ids", 50, 50, zzcf.zza);
        zzao = zza("measurement.max_bundles_per_iteration", 1, 1, zzci.zza);
        zzap = zza("measurement.validation.internal_limits_internal_event_params", false, false, zzch.zza);
        zzaq = zza("measurement.referrer.enable_logging_install_referrer_cmp_from_apk", false, false, zzcj.zza);
        zzar = zza("measurement.client.sessions.session_id_enabled", true, true, zzcm.zza);
        zzas = zza("measurement.service.sessions.session_number_enabled", true, true, zzcl.zza);
        zzat = zza("measurement.client.sessions.background_sessions_enabled", true, true, zzco.zza);
        zzau = zza("measurement.client.sessions.remove_expired_session_properties_enabled", true, true, zzcn.zza);
        zzav = zza("measurement.service.sessions.session_number_backfill_enabled", true, true, zzcq.zza);
        zzaw = zza("measurement.service.sessions.remove_disabled_session_number", true, true, zzcp.zza);
        zzax = zza("measurement.client.sessions.start_session_before_view_screen", true, true, zzcs.zza);
        zzay = zza("measurement.client.sessions.check_on_startup", true, true, zzcr.zza);
        zzaz = zza("measurement.collection.firebase_global_collection_flag_enabled", true, true, zzcu.zza);
        zzba = zza("measurement.collection.efficient_engagement_reporting_enabled_2", false, false, zzcw.zza);
        zzbb = zza("measurement.collection.redundant_engagement_removal_enabled", false, false, zzcv.zza);
        zzbc = zza("measurement.personalized_ads_signals_collection_enabled", true, true, zzcy.zza);
        zzbd = zza("measurement.personalized_ads_property_translation_enabled", true, true, zzcx.zza);
        zzbe = zza("measurement.experiment.enable_experiment_reporting", true, true, zzda.zza);
        zzbf = zza("measurement.collection.log_event_and_bundle_v2", true, true, zzcz.zza);
        zzbg = zza("measurement.quality.checksum", false, false, null);
        zzbh = zza("measurement.module.collection.conditionally_omit_admob_app_id", true, true, zzdc.zza);
        zzbi = zza("measurement.sdk.dynamite.use_dynamite2", false, false, zzdb.zza);
        zzbj = zza("measurement.sdk.dynamite.allow_remote_dynamite", false, false, zzde.zza);
        zzbk = zza("measurement.sdk.collection.validate_param_names_alphabetical", false, false, zzdd.zza);
        zzbl = zza("measurement.collection.event_safelist", true, true, zzdf.zza);
        zzbm = zza("measurement.service.audience.scoped_filters_v27", true, true, zzdi.zza);
        zzbn = zza("measurement.service.audience.session_scoped_event_aggregates", true, true, zzdh.zza);
        zzbo = zza("measurement.service.audience.session_scoped_user_engagement", true, true, zzdk.zza);
        zzbp = zza("measurement.service.audience.scoped_engagement_removal_when_session_expired", true, true, zzdj.zza);
        zzbq = zza("measurement.client.audience.scoped_engagement_removal_when_session_expired", true, true, zzdm.zza);
        zzbr = zza("measurement.service.audience.remove_disabled_session_scoped_user_engagement", false, false, zzdl.zza);
        zzbs = zza("measurement.service.audience.use_bundle_timestamp_for_property_filters", true, true, zzdo.zza);
        zzbt = zza("measurement.service.audience.fix_prepending_previous_sequence_timestamp", true, true, zzdn.zza);
        zzdj = zza("measurement.service.audience.invalidate_config_cache_after_app_unisntall", true, true, zzdq.zza);
        zzbu = zza("measurement.service.audience.fix_skip_audience_with_failed_filters", true, true, zzds.zza);
        zzbv = zza("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", false, false, zzdr.zza);
        zzbw = zza("measurement.audience.refresh_event_count_filters_timestamp", false, false, zzdu.zza);
        zzbx = zza("measurement.audience.use_bundle_timestamp_for_event_count_filters", false, false, zzdt.zza);
        zzby = zza("measurement.sdk.collection.retrieve_deeplink_from_bow_2", true, true, zzdw.zza);
        zzbz = zza("measurement.app_launch.event_ordering_fix", false, false, zzdv.zza);
        zzca = zza("measurement.sdk.collection.last_deep_link_referrer2", true, true, zzdy.zza);
        zzcb = zza("measurement.sdk.collection.last_deep_link_referrer_campaign2", false, false, zzdx.zza);
        zzcc = zza("measurement.sdk.collection.last_gclid_from_referrer2", false, false, zzea.zza);
        zzcd = zza("measurement.sdk.collection.worker_thread_referrer", true, true, zzdz.zza);
        zzce = zza("measurement.sdk.collection.enable_extend_user_property_size", true, true, zzeb.zza);
        zzcf = zza("measurement.upload.file_lock_state_check", false, false, zzee.zza);
        zzcg = zza("measurement.sampling.calculate_bundle_timestamp_before_sampling", true, true, zzed.zza);
        zzch = zza("measurement.ga.ga_app_id", false, false, zzeg.zza);
        zzci = zza("measurement.lifecycle.app_backgrounded_tracking", true, true, zzef.zza);
        zzcj = zza("measurement.lifecycle.app_in_background_parameter", false, false, zzei.zza);
        zzck = zza("measurement.integration.disable_firebase_instance_id", false, false, zzeh.zza);
        zzcl = zza("measurement.lifecycle.app_backgrounded_engagement", false, false, zzek.zza);
        zzcm = zza("measurement.service.fix_gmp_version", false, false, zzej.zza);
        zzcn = zza("measurement.collection.service.update_with_analytics_fix", false, false, zzem.zza);
        zzco = zza("measurement.service.disable_install_state_reporting", true, true, zzeo.zza);
        zzcp = zza("measurement.service.use_appinfo_modified", false, false, zzen.zza);
        zzcq = zza("measurement.client.firebase_feature_rollout.v1.enable", true, true, zzeq.zza);
        zzcr = zza("measurement.client.sessions.check_on_reset_and_enable", false, false, zzep.zza);
        zzcs = zza("measurement.config.string.always_update_disk_on_set", false, false, zzes.zza);
        zzct = zza("measurement.scheduler.task_thread.cleanup_on_exit", false, false, zzer.zza);
        zzcu = zza("measurement.upload.file_truncate_fix", false, false, zzeu.zza);
        zzcv = zza("measurement.lifecycle.app_background_timestamp_when_backgrounded", true, true, zzet.zza);
        zzcw = zza("measurement.engagement_time_main_thread", true, true, zzew.zza);
        zzcx = zza("measurement.sdk.referrer.delayed_install_referrer_api", false, false, zzev.zza);
        zzcy = zza("measurement.logging.improved_messaging_q4_2019_client", true, true, zzat.zza);
        zzcz = zza("measurement.logging.improved_messaging_q4_2019_service", true, true, zzaw.zza);
        zzda = zza("measurement.gold.enhanced_ecommerce.format_logs", false, false, zzav.zza);
        zzdb = zza("measurement.gold.enhanced_ecommerce.nested_param_daily_event_count", false, false, zzay.zza);
        zzdc = zza("measurement.gold.enhanced_ecommerce.upload_nested_complex_events", false, false, zzax.zza);
        zzdd = zza("measurement.gold.enhanced_ecommerce.log_nested_complex_events.dev", false, false, zzba.zza);
        zzde = zza("measurement.gold.enhanced_ecommerce.updated_schema.client.dev", false, false, zzaz.zza);
        zzdf = zza("measurement.gold.enhanced_ecommerce.updated_schema.service", false, false, zzbc.zza);
        zzdk = zza("measurement.collection.synthetic_data_mitigation", false, false, zzbb.zza);
        zzdg = zza("measurement.collection.configurable_service_limits.dev", false, false, zzbe.zza);
    }
}
