package com.box.android.domain.configuration;

import java.util.HashMap;

/* JADX INFO: loaded from: classes11.dex */
public final class BoxConfigConstants {
    public static final String BOX_DOMAIN_URL = "https://www.box.com";
    public static final String CONFIG_AMPLITUDE_API_KEY = "c6eb3d709c5c30ca80c0381080bcc254";
    static final boolean CONFIG_ANALYTICS_DEBUGGING_ENABLED = false;
    public static final String CONFIG_API_URL_HOSTNAME = "mobile-api.box.com";
    public static final String CONFIG_API_URL_HOSTNAME_FEDRAMP_COMPLIANT = "mobile-api.box-gov.com";
    static final String CONFIG_API_URL_SCHEME = "https";
    public static final String CONFIG_BOX_CANVAS_OAUTH_PATH = "api/oauth2/authorize";
    public static final String CONFIG_BOX_CANVAS_REDIRECT_URL = "https://canvas.inside-box.net";
    public static final String CONFIG_BOX_CANVAS_SERVICE_CLIENT_ID = "8ep60teeeawirs5231dc03w82awybrog";
    public static final String CONFIG_BOX_CANVAS_URL_PATH = "app-api/canvas-web/canvas";
    static final String CONFIG_BOX_NOTES_OAUTH_PATH = "api/oauth2/authorize";
    static final String CONFIG_BOX_NOTES_SERVICE_CLIENT_ID = "qviptxzetdwyt2o3hyumj8vml2jlxo7k";
    public static final String CONFIG_BOX_NOTES_URL_HOSTNAME = "notes.services.box.com";
    public static final String CONFIG_BOX_NOTES_URL_HOSTNAME_FEDRAMP_COMPLIANT = "notes.services.box-gov.com";
    static final String CONFIG_BOX_NOTES_URL_PATH = "note";
    static final String CONFIG_BOX_NOTES_URL_SCHEME = "https";
    public static final String CONFIG_CLIENT_TYPE = "config_key_client_type";
    public static final boolean CONFIG_EMM_ACCOUNT_SWITCHING_ENABLED = false;
    static final boolean CONFIG_ENABLE_CREATE_BOX_NOTES = true;
    static final boolean CONFIG_ENABLE_EVENTS_POLLING_FOR_BOX_USERS = false;
    static final boolean CONFIG_ENABLE_EVENTS_POLLING_FOR_NON_BOX_USERS = false;
    static final boolean CONFIG_ENABLE_OPEN_BOX_NOTES = true;
    static final boolean CONFIG_ENABLE_WIDGET = true;
    static String[] CONFIG_FALLBACK_PATHS = {"/api/oauth2/authorize"};
    static final String CONFIG_GCM_CLIENT_ID = "254125847185-7g6dknirco1uv2q1skgkcuq1ui1fmpv6.apps.googleusercontent.com";
    static final String CONFIG_GCM_PROJECT_ID = "254125847185";
    static final boolean CONFIG_GOOGLE_ALPHA_GROUP_ENABLED = true;
    static final String CONFIG_GOOGLE_ALPHA_GROUP_PLAY_STORE_URL = "https://play.google.com/apps/testing/com.box.android ";
    static final String CONFIG_GOOGLE_ALPHA_GROUP_URL = "https://groups.google.com/forum/#!forum/box-android-app-alpha/join";
    static final String CONFIG_GOOGLE_TAG_MANAGER_ID = "GTM-TWBM9F";
    static final String CONFIG_HARDWARE_ACCELERATED = "false";
    public static final String CONFIG_HELP_CENTER_URL = "https://support.box.com/hc/en-us/sections/21356693663763-Box-Mobile";
    public static final String CONFIG_KEY_ACCOUNT_SWITCHING_ENABLED_BOOL = "config_multi_account_switching_enabled";
    public static final String CONFIG_KEY_API_URL_HOSTNAME = "config_key_api_url_hostname";
    public static final String CONFIG_KEY_API_URL_SCHEME = "config_key_api_url_scheme";
    public static final String CONFIG_KEY_APP_NAME = "config_key_app_name";
    public static final String CONFIG_KEY_BOX_CANVAS_OAUTH_PATH = "config_key_box_canvas_oauth_path";
    public static final String CONFIG_KEY_BOX_CANVAS_REDIRECT_URL = "config_key_box_canvas_redirect_url";
    public static final String CONFIG_KEY_BOX_CANVAS_SERVICE_CLIENT_ID = "config_key_box_canvas_service_client_id";
    public static final String CONFIG_KEY_BOX_CANVAS_URL_PATH = "config_key_box_canvas_url_path";
    public static final String CONFIG_KEY_BOX_NOTES_OAUTH_PATH = "config_key_box_notes_oauth_path";
    public static final String CONFIG_KEY_BOX_NOTES_SERVICE_CLIENT_ID = "config_key_box_notes_service_client_id";
    public static final String CONFIG_KEY_BOX_NOTES_URL_HOSTNAME = "config_key_box_notes_url_hostname";
    public static final String CONFIG_KEY_BOX_NOTES_URL_PATH = "config_key_box_notes_url_path";
    public static final String CONFIG_KEY_BOX_NOTES_URL_SCHEME = "config_key_box_notes_url_scheme";
    public static final String CONFIG_KEY_CLIENT_ID = "config_key_client_key";
    public static final String CONFIG_KEY_CLIENT_SECRET = "config_key_client_secret";
    public static final String CONFIG_KEY_ENABLE_CREATE_BOX_NOTES_BOOL = "config_key_enable_create_box_notes";
    public static final String CONFIG_KEY_ENABLE_EVENTS_POLLING_FOR_BOX_USERS_BOOL = "config_key_enable_events_polling_for_box_users";
    public static final String CONFIG_KEY_ENABLE_EVENTS_POLLING_FOR_NON_BOX_USERS_BOOL = "config_key_enable_events_polling_for_non_box_users";
    public static final String CONFIG_KEY_ENABLE_OPEN_BOX_NOTES_BOOL = "config_key_enable_open_box_notes";
    public static final String CONFIG_KEY_ENABLE_WIDGET_BOOL = "config_key_enable_widget";
    public static final String CONFIG_KEY_FALLBACK_PATHS_ARRAY = "config_key_fallback_paths";
    public static final String CONFIG_KEY_GCM_CLIENT_ID = "config_key_gcm_client_id";
    public static final String CONFIG_KEY_GCM_PROJECT_ID = "config_key_gcm_project_id";
    public static final String CONFIG_KEY_GOOGLE_ALPHA_GROUP_ENABLED_BOOL = "config_key_google_alpha_group_enabled";
    public static final String CONFIG_KEY_GOOGLE_ALPHA_GROUP_PLAY_STORE_URL = "config_key_google_alpha_group_play_store_url";
    public static final String CONFIG_KEY_GOOGLE_ALPHA_GROUP_URL = "config_key_google_alpha_group_url";
    public static final String CONFIG_KEY_GOOGLE_TAG_MANAGER_ID = "config_key_google_tag_manager_id";
    public static final String CONFIG_KEY_HARDWARE_ACCELERATED = "config_key_hardware_accelerated";
    public static final String CONFIG_KEY_HELP_CENTER_URL = "config_key_help_center_url";
    public static final String CONFIG_KEY_KILL_APP_ON_LOGOUT_BOOL = "config_key_kill_app_on_logout";
    public static final String CONFIG_KEY_MARKET_URL = "config_key_market_url";
    public static final String CONFIG_KEY_MIME_TYPE_ADDON_URL = "config_key_mime_type_addon_url";
    public static final String CONFIG_KEY_OAUTH_URL_AUTHORITY = "config_key_oauth_url_authority";
    public static final String CONFIG_KEY_PACKAGE_ID = "config_key_package_id";
    public static final String CONFIG_KEY_PRIVACY_POLICY_URL = "config_key_privacy_policy_url";
    public static final String CONFIG_KEY_REDIRECT_URL = "config_key_redirect_url";
    public static final String CONFIG_KEY_SHOULD_SHOW_WRITE_A_REVIEW_BUTTON_BOOL = "config_key_should_show_write_a_review_button";
    public static final String CONFIG_KEY_SURVEY_URL = "config_key_survey_url";
    public static final String CONFIG_KEY_TERMS_OF_SERVICE_URL = "config_key_terms_of_service_url";
    public static final String CONFIG_KEY_UTEST_BOOL = "config_key_utest";
    public static final String CONFIG_KEY_V2_API_URL_HOSTNAME = "config_key_v2_api_url_hostname";
    public static final String CONFIG_KEY_V2_API_URL_PATH = "config_key_v2_api_url_path";
    public static final String CONFIG_KEY_V2_API_URL_SCHEME = "config_key_v2_api_url_scheme";
    public static final String CONFIG_KEY_V2_UPLOAD_URL_HOSTNAME = "config_key_v2_upload_url_hostname";
    public static final String CONFIG_KEY_V2_UPLOAD_URL_PATH = "config_key_v2_upload_url_path";
    public static final String CONFIG_KEY_V2_UPLOAD_URL_SCHEME = "config_key_v2_upload_url_scheme";
    static final String CONFIG_MARKET_URL = "market://details?id=com.box.android";
    public static final String CONFIG_MIME_TYPE_ADDON_URL = "https://www.box.com/android_mime_type_addons_xml";
    public static final String CONFIG_MIME_TYPE_ADDON_URL_FEDRAMP_COMPLIANT = "https://www.box-gov.com/android_mime_type_addons_xml";
    public static final String CONFIG_OAUTH_URL_AUTHORITY = "account.box.com";
    public static final String CONFIG_OAUTH_URL_AUTHORITY_FEDRAMP_COMPLIANT = "account.box-gov.com";
    static final String CONFIG_PACKAGE_ID = "com.box.android";
    public static final String CONFIG_PENDO_API_KEY = "eyJhbGciOiJSUzI1NiIsImtpZCI6IiIsInR5cCI6IkpXVCJ9.eyJkYXRhY2VudGVyIjoidXMiLCJrZXkiOiJhZGEwOTMzYjNiNzQxNTczNTNhNTRhNWEyYWZjYzlkOWY3OWUxMGI1MDA4OTBjOTYzYjkyMGFkZmZlYmExZjExYjFmNDE3NGViMmQzMjY1ZWVmNWYyOWM2MmYzYzgyOTgzZmQyYzJhNDBlNzEwMTIzODJmODU3ZDliZmIyZTJlNTQ1NzIwZWZhN2NhODcyMThkY2YzNzMzYTVkYWRjZTdlZjFlOTgxMmE5MTI4Yzg0NzY2M2VjM2IwODM5MmYyMzhlM2RkNjI0YjNkMjQxNzQ5MGNjOWZjNmUzNzE1ZTgyOC44NWRlNzI4MTM2ZGJiOWYyYzI2NDhhMjU2YjZlYTBlMC5lNTNkNzYxZjQ0ZDFhOWNkOWNhODk2YzA1OWQyNDRmNTAzNDFkZGEzNGRiNjg1MzdhYmNlYTFjMTNmNjBjN2Q1In0.BOFIXEyeiA8EZZs9sLOlLVY_rP-k6Vfke6LlM5XH7q7pq5DbMokPCfPfJBH5vvVWXjJfLUh1_CWvLpvVC5zH2L7S5SOZdzCqrMTHaG09XAbEwcWM8JEEXDF1Yap-CiXLlGWLMP35ONoXiPFr2XCuwRSa79DESvw6d5xfGiXFC40";
    public static final String CONFIG_PRIVACY_POLICY_URL = "https://account.box.com/legal_text/privacy_policy";
    public static final String CONFIG_PRIVACY_POLICY_URL_FEDRAMP_COMPLIANT = "https://account.box-gov.com/legal_text/privacy_policy";
    static final String CONFIG_REDIRECT_URL = "boxlogin://login";
    public static final String CONFIG_SDK_AIRWATCH_CLIENT_ID = "w2ndash5bh5zgeq3unw0km4bwakdmx8f";
    public static final String CONFIG_SDK_AIRWATCH_CLIENT_SECRET = "0SjDcsqugEjE3LZbQpnbxw2tBYeQG7s0";
    public static final String CONFIG_SDK_AIRWATCH_TABLET_CLIENT_ID = "a3q8sad7xelv4b4hpvmeqj1ufmm1qzzm";
    public static final String CONFIG_SDK_AIRWATCH_TABLET_CLIENT_SECRET = "AubFhmTFn2azpHcsMThzlU9MbtogyRr0";
    public static final String CONFIG_SDK_DEFAULT_CLIENT_ID = "1y4ddq8mohgjyat6767yda5zca9ytxu3";
    public static final String CONFIG_SDK_DEFAULT_CLIENT_SECRET = "H7aF3eXr4KxoomlFKiFx8HRheBBlfYlo";
    public static final String CONFIG_SDK_DEFAULT_TABLET_CLIENT_ID = "zfyodl2ap2fi3qm40t50i9xl7de83fq0";
    public static final String CONFIG_SDK_DEFAULT_TABLET_CLIENT_SECRET = "Mxi0gLhf8FOSuGtQF8TKaXo19YV6Pqmm";
    public static final String CONFIG_SDK_EMM_CLIENT_ID = "w2ndash5bh5zgeq3unw0km4bwakdmx8f";
    public static final String CONFIG_SDK_EMM_CLIENT_SECRET = "0SjDcsqugEjE3LZbQpnbxw2tBYeQG7s0";
    public static final String CONFIG_SDK_EMM_TABLET_CLIENT_ID = "a3q8sad7xelv4b4hpvmeqj1ufmm1qzzm";
    public static final String CONFIG_SDK_EMM_TABLET_CLIENT_SECRET = "AubFhmTFn2azpHcsMThzlU9MbtogyRr0";
    public static final String CONFIG_SDK_MOBILEIRON_CLIENT_ID = "hmmjqsifm0kbfuzeojiuhno5y4qu1gu2";
    public static final String CONFIG_SDK_MOBILEIRON_CLIENT_SECRET = "I6abu84Slu7dHGsZyENtJC04xI2Mmanv";
    public static final String CONFIG_SDK_MOBILEIRON_TABLET_CLIENT_ID = "hmmjqsifm0kbfuzeojiuhno5y4qu1gu2";
    public static final String CONFIG_SDK_MOBILEIRON_TABLET_CLIENT_SECRET = "I6abu84Slu7dHGsZyENtJC04xI2Mmanv";
    static final boolean CONFIG_SHOULD_SHOW_WRITE_A_REVIEW_BUTTON = true;
    public static final String CONFIG_SURVEY_URL = "https://www.box.com/mobilesurvey";
    public static final String CONFIG_SURVEY_URL_FEDRAMP_COMPLIANT = "https://www.box-gov.com/mobilesurvey";
    public static final String CONFIG_TERMS_OF_SERVICE_URL = "https://account.box.com/legal_text/tos";
    public static final String CONFIG_TERMS_OF_SERVICE_URL_FEDRAMP_COMPLIANT = "https://account.box-gov.com/legal_text/tos";
    static final boolean CONFIG_UTEST = false;
    public static final String CONFIG_V2_API_URL_HOSTNAME = "account.box.com";
    public static final String CONFIG_V2_API_URL_HOSTNAME_FEDRAMP_COMPLIANT = "account.box-gov.com";
    static final String CONFIG_V2_API_URL_PATH = "/2.0/";
    static final String CONFIG_V2_API_URL_SCHEME = "https";
    public static final String CONFIG_V2_UPLOAD_URL_HOSTNAME = "upload.box.com";
    public static final String CONFIG_V2_UPLOAD_URL_HOSTNAME_FEDRAMP_COMPLIANT = "upload.box-gov.com";
    static final String CONFIG_V2_UPLOAD_URL_PATH = "/api/2.0/";
    static final String CONFIG_V2_UPLOAD_URL_SCHEME = "https";
    static final HashMap<String, Object> DEFAULT_CONFIG_MAP;
    public static final String DEVPOD_HOST_NAME_SUBSTRING = "monolith-devpod.apps-global.gcp001.dev.box.net";

    static {
        HashMap<String, Object> map = new HashMap<>();
        DEFAULT_CONFIG_MAP = map;
        map.put(CONFIG_KEY_OAUTH_URL_AUTHORITY, "account.box.com");
        map.put(CONFIG_KEY_REDIRECT_URL, "boxlogin://login");
        map.put(CONFIG_KEY_API_URL_SCHEME, "https");
        map.put(CONFIG_KEY_API_URL_HOSTNAME, CONFIG_API_URL_HOSTNAME);
        map.put(CONFIG_KEY_V2_API_URL_SCHEME, "https");
        map.put(CONFIG_KEY_V2_API_URL_HOSTNAME, "account.box.com");
        map.put(CONFIG_KEY_V2_API_URL_PATH, CONFIG_V2_API_URL_PATH);
        map.put(CONFIG_KEY_V2_UPLOAD_URL_SCHEME, "https");
        map.put(CONFIG_KEY_V2_UPLOAD_URL_HOSTNAME, CONFIG_V2_UPLOAD_URL_HOSTNAME);
        map.put(CONFIG_KEY_V2_UPLOAD_URL_PATH, CONFIG_V2_UPLOAD_URL_PATH);
        map.put(CONFIG_KEY_BOX_NOTES_URL_SCHEME, "https");
        map.put(CONFIG_KEY_BOX_NOTES_URL_HOSTNAME, CONFIG_BOX_NOTES_URL_HOSTNAME);
        map.put(CONFIG_KEY_BOX_NOTES_URL_PATH, CONFIG_BOX_NOTES_URL_PATH);
        map.put(CONFIG_KEY_BOX_NOTES_SERVICE_CLIENT_ID, CONFIG_BOX_NOTES_SERVICE_CLIENT_ID);
        map.put(CONFIG_KEY_BOX_NOTES_OAUTH_PATH, "api/oauth2/authorize");
        map.put(CONFIG_KEY_MIME_TYPE_ADDON_URL, CONFIG_MIME_TYPE_ADDON_URL);
        map.put(CONFIG_KEY_SURVEY_URL, CONFIG_SURVEY_URL);
        map.put(CONFIG_KEY_HARDWARE_ACCELERATED, "false");
        map.put(CONFIG_KEY_GCM_PROJECT_ID, CONFIG_GCM_PROJECT_ID);
        map.put(CONFIG_KEY_GCM_CLIENT_ID, CONFIG_GCM_CLIENT_ID);
        map.put(CONFIG_KEY_MARKET_URL, CONFIG_MARKET_URL);
        map.put(CONFIG_KEY_ENABLE_WIDGET_BOOL, true);
        map.put(CONFIG_KEY_SHOULD_SHOW_WRITE_A_REVIEW_BUTTON_BOOL, true);
        map.put(CONFIG_KEY_GOOGLE_ALPHA_GROUP_ENABLED_BOOL, true);
        map.put(CONFIG_KEY_GOOGLE_ALPHA_GROUP_URL, CONFIG_GOOGLE_ALPHA_GROUP_URL);
        map.put(CONFIG_KEY_GOOGLE_ALPHA_GROUP_PLAY_STORE_URL, CONFIG_GOOGLE_ALPHA_GROUP_PLAY_STORE_URL);
        map.put(CONFIG_KEY_HELP_CENTER_URL, CONFIG_HELP_CENTER_URL);
        map.put(CONFIG_KEY_PRIVACY_POLICY_URL, CONFIG_PRIVACY_POLICY_URL);
        map.put(CONFIG_KEY_TERMS_OF_SERVICE_URL, CONFIG_TERMS_OF_SERVICE_URL);
        map.put(CONFIG_KEY_ENABLE_OPEN_BOX_NOTES_BOOL, true);
        map.put(CONFIG_KEY_ENABLE_CREATE_BOX_NOTES_BOOL, true);
        map.put(CONFIG_KEY_UTEST_BOOL, false);
        map.put(CONFIG_KEY_ENABLE_EVENTS_POLLING_FOR_BOX_USERS_BOOL, false);
        map.put(CONFIG_KEY_ENABLE_EVENTS_POLLING_FOR_NON_BOX_USERS_BOOL, false);
        map.put(CONFIG_KEY_GOOGLE_TAG_MANAGER_ID, CONFIG_GOOGLE_TAG_MANAGER_ID);
        map.put(CONFIG_KEY_PACKAGE_ID, "com.box.android");
        map.put(CONFIG_KEY_FALLBACK_PATHS_ARRAY, CONFIG_FALLBACK_PATHS);
        map.put(CONFIG_KEY_BOX_CANVAS_SERVICE_CLIENT_ID, CONFIG_BOX_CANVAS_SERVICE_CLIENT_ID);
        map.put(CONFIG_KEY_BOX_CANVAS_OAUTH_PATH, "api/oauth2/authorize");
        map.put(CONFIG_KEY_BOX_CANVAS_URL_PATH, CONFIG_BOX_CANVAS_URL_PATH);
        map.put(CONFIG_KEY_BOX_CANVAS_REDIRECT_URL, CONFIG_BOX_CANVAS_REDIRECT_URL);
    }
}
