package com.pspdfkit.ui.toolbar.grouping.presets;

import com.pspdfkit.R;
import kotlin.Metadata;

/* JADX INFO: loaded from: classes3.dex */
@Metadata(d1 = {"\u0000\u0014\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0002\b\u000b\bÇ\u0002\u0018\u00002\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0002\u0010\u0003R\u0010\u0010\u0004\u001a\u00020\u00058\u0006X\u0087\u0004¢\u0006\u0002\n\u0000R\u0010\u0010\u0006\u001a\u00020\u00058\u0006X\u0087\u0004¢\u0006\u0002\n\u0000R\u0010\u0010\u0007\u001a\u00020\u00058\u0006X\u0087\u0004¢\u0006\u0002\n\u0000R\u0010\u0010\b\u001a\u00020\u00058\u0006X\u0087\u0004¢\u0006\u0002\n\u0000R\u0010\u0010\t\u001a\u00020\u00058\u0006X\u0087\u0004¢\u0006\u0002\n\u0000R\u0010\u0010\n\u001a\u00020\u00058\u0006X\u0087\u0004¢\u0006\u0002\n\u0000R\u0010\u0010\u000b\u001a\u00020\u00058\u0006X\u0087\u0004¢\u0006\u0002\n\u0000R\u0010\u0010\f\u001a\u00020\u00058\u0006X\u0087\u0004¢\u0006\u0002\n\u0000R\u0010\u0010\r\u001a\u00020\u00058\u0006X\u0087\u0004¢\u0006\u0002\n\u0000R\u0010\u0010\u000e\u001a\u00020\u00058\u0006X\u0087\u0004¢\u0006\u0002\n\u0000R\u0010\u0010\u000f\u001a\u00020\u00058\u0006X\u0087\u0004¢\u0006\u0002\n\u0000¨\u0006\u0010"}, d2 = {"Lcom/pspdfkit/ui/toolbar/grouping/presets/AnnotationCreationToolbarItemGroups;", "", "<init>", "()V", "MARKUP_GROUP", "Lcom/pspdfkit/ui/toolbar/grouping/presets/MenuItem;", "MARKUP_GROUP_CALLOUT", "MARKUP_GROUP_EXTRA", "WRITING_GROUP", "WRITING_AND_MULTIMEDIA_GROUP", "DRAWING_GROUP", "DRAWING_GROUP_NO_ERASER", "DRAWING_GROUP_PLUS_MEASUREMENTS", "MULTIMEDIA_GROUP", "UNDO_REDO_GROUP", "MEASUREMENTS_GROUP", "sdk-nutrient"}, k = 1, mv = {2, 3, 0}, xi = 48)
public final class AnnotationCreationToolbarItemGroups {
    public static final AnnotationCreationToolbarItemGroups INSTANCE = new AnnotationCreationToolbarItemGroups();
    public static final MenuItem MARKUP_GROUP = new MenuItem(R.id.pspdf__annotation_toolbar_group_markup, new int[]{R.id.pspdf__annotation_toolbar_item_highlight, R.id.pspdf__annotation_toolbar_item_squiggly, R.id.pspdf__annotation_toolbar_item_strikeout, R.id.pspdf__annotation_toolbar_item_underline, R.id.pspdf__annotation_toolbar_item_redaction});
    public static final MenuItem MARKUP_GROUP_CALLOUT = new MenuItem(R.id.pspdf__annotation_toolbar_group_markup, new int[]{R.id.pspdf__annotation_toolbar_item_highlight, R.id.pspdf__annotation_toolbar_item_squiggly, R.id.pspdf__annotation_toolbar_item_strikeout, R.id.pspdf__annotation_toolbar_item_underline, R.id.pspdf__annotation_toolbar_item_redaction, R.id.pspdf__annotation_toolbar_item_freetext_callout});
    public static final MenuItem MARKUP_GROUP_EXTRA = new MenuItem(R.id.pspdf__annotation_toolbar_group_markup, new int[]{R.id.pspdf__annotation_toolbar_item_highlight, R.id.pspdf__annotation_toolbar_item_squiggly, R.id.pspdf__annotation_toolbar_item_strikeout, R.id.pspdf__annotation_toolbar_item_underline, R.id.pspdf__annotation_toolbar_item_redaction, R.id.pspdf__annotation_toolbar_item_note, R.id.pspdf__annotation_toolbar_item_instant_comment_marker, R.id.pspdf__annotation_toolbar_item_freetext, R.id.pspdf__annotation_toolbar_item_freetext_callout, R.id.pspdf__annotation_toolbar_item_signature, R.id.pspdf__annotation_toolbar_item_image, R.id.pspdf__annotation_toolbar_item_stamp, R.id.pspdf__annotation_toolbar_item_camera, R.id.pspdf__annotation_toolbar_item_sound});
    public static final MenuItem WRITING_GROUP = new MenuItem(R.id.pspdf__annotation_toolbar_group_writing, new int[]{R.id.pspdf__annotation_toolbar_item_note, R.id.pspdf__annotation_toolbar_item_instant_comment_marker, R.id.pspdf__annotation_toolbar_item_freetext, R.id.pspdf__annotation_toolbar_item_freetext_callout, R.id.pspdf__annotation_toolbar_item_signature});
    public static final MenuItem WRITING_AND_MULTIMEDIA_GROUP = new MenuItem(R.id.pspdf__annotation_toolbar_group_writing, new int[]{R.id.pspdf__annotation_toolbar_item_note, R.id.pspdf__annotation_toolbar_item_instant_comment_marker, R.id.pspdf__annotation_toolbar_item_freetext, R.id.pspdf__annotation_toolbar_item_freetext_callout, R.id.pspdf__annotation_toolbar_item_signature, R.id.pspdf__annotation_toolbar_item_image, R.id.pspdf__annotation_toolbar_item_stamp, R.id.pspdf__annotation_toolbar_item_camera, R.id.pspdf__annotation_toolbar_item_sound});
    public static final MenuItem DRAWING_GROUP = new MenuItem(R.id.pspdf__annotation_toolbar_group_drawing, new int[]{R.id.pspdf__annotation_toolbar_item_ink_pen, R.id.pspdf__annotation_toolbar_item_ink_highlighter, R.id.pspdf__annotation_toolbar_item_magic_ink, R.id.pspdf__annotation_toolbar_item_line, R.id.pspdf__annotation_toolbar_item_line_arrow, R.id.pspdf__annotation_toolbar_item_square, R.id.pspdf__annotation_toolbar_item_circle, R.id.pspdf__annotation_toolbar_item_polygon, R.id.pspdf__annotation_toolbar_item_cloudy, R.id.pspdf__annotation_toolbar_item_polyline, R.id.pspdf__annotation_toolbar_item_eraser, R.id.pspdf__annotation_toolbar_item_multi_selection});
    public static final MenuItem DRAWING_GROUP_NO_ERASER = new MenuItem(R.id.pspdf__annotation_toolbar_group_drawing, new int[]{R.id.pspdf__annotation_toolbar_item_ink_pen, R.id.pspdf__annotation_toolbar_item_ink_highlighter, R.id.pspdf__annotation_toolbar_item_magic_ink, R.id.pspdf__annotation_toolbar_item_line, R.id.pspdf__annotation_toolbar_item_line_arrow, R.id.pspdf__annotation_toolbar_item_square, R.id.pspdf__annotation_toolbar_item_circle, R.id.pspdf__annotation_toolbar_item_polygon, R.id.pspdf__annotation_toolbar_item_cloudy, R.id.pspdf__annotation_toolbar_item_polyline, R.id.pspdf__annotation_toolbar_item_multi_selection});
    public static final MenuItem DRAWING_GROUP_PLUS_MEASUREMENTS = new MenuItem(R.id.pspdf__annotation_toolbar_group_drawing, new int[]{R.id.pspdf__annotation_toolbar_item_ink_pen, R.id.pspdf__annotation_toolbar_item_ink_highlighter, R.id.pspdf__annotation_toolbar_item_magic_ink, R.id.pspdf__annotation_toolbar_item_line, R.id.pspdf__annotation_toolbar_item_line_arrow, R.id.pspdf__annotation_toolbar_item_square, R.id.pspdf__annotation_toolbar_item_circle, R.id.pspdf__annotation_toolbar_item_polygon, R.id.pspdf__annotation_toolbar_item_cloudy, R.id.pspdf__annotation_toolbar_item_polyline, R.id.pspdf__annotation_toolbar_item_measurement_distance, R.id.pspdf__annotation_toolbar_item_measurement_perimeter, R.id.pspdf__annotation_toolbar_item_measurement_area_polygon, R.id.pspdf__annotation_toolbar_item_measurement_area_ellipse, R.id.pspdf__annotation_toolbar_item_measurement_area_rect, R.id.pspdf__annotation_toolbar_item_eraser, R.id.pspdf__annotation_toolbar_item_multi_selection, R.id.pspdf__annotation_toolbar_item_measurement_scale_calibration});
    public static final MenuItem MULTIMEDIA_GROUP = new MenuItem(R.id.pspdf__annotation_toolbar_group_multimedia, new int[]{R.id.pspdf__annotation_toolbar_item_image, R.id.pspdf__annotation_toolbar_item_stamp, R.id.pspdf__annotation_toolbar_item_camera, R.id.pspdf__annotation_toolbar_item_sound});
    public static final MenuItem UNDO_REDO_GROUP = new MenuItem(R.id.pspdf__annotation_toolbar_group_undo_redo, new int[]{R.id.pspdf__annotation_toolbar_item_undo, R.id.pspdf__annotation_toolbar_item_redo});
    public static final MenuItem MEASUREMENTS_GROUP = new MenuItem(R.id.pspdf__annotation_toolbar_group_measurement, new int[]{R.id.pspdf__annotation_toolbar_item_measurement_distance, R.id.pspdf__annotation_toolbar_item_measurement_perimeter, R.id.pspdf__annotation_toolbar_item_measurement_area_polygon, R.id.pspdf__annotation_toolbar_item_measurement_area_ellipse, R.id.pspdf__annotation_toolbar_item_measurement_area_rect, R.id.pspdf__annotation_toolbar_item_measurement_scale_calibration});
    public static final int $stable = 8;

    private AnnotationCreationToolbarItemGroups() {
    }
}
